//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcadesUserInterfacePattern.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcePtBR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcePtBR() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcadesUserInterfacePattern.Server.Resources.ResourcePtBR", typeof(ResourcePtBR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clique-me.
        /// </summary>
        internal static string CounterPageLabelButtonClick {
            get {
                return ResourceManager.GetString("CounterPageLabelButtonClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contagem atual.
        /// </summary>
        internal static string CounterPageLabelCurrrentCount {
            get {
                return ResourceManager.GetString("CounterPageLabelCurrrentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contador.
        /// </summary>
        internal static string CounterPageTitle {
            get {
                return ResourceManager.GetString("CounterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ola, Mundo!.
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tema escuro.
        /// </summary>
        internal static string HeaderLabelDarkTheme {
            get {
                return ResourceManager.GetString("HeaderLabelDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Como o Blazor está funcionando para você? Por favor, responda à nossa breve pesquisa e diga-nos o que você pensa..
        /// </summary>
        internal static string HomeText {
            get {
                return ResourceManager.GetString("HomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carregando....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contador.
        /// </summary>
        internal static string MenuCounter {
            get {
                return ResourceManager.GetString("MenuCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Obter dados.
        /// </summary>
        internal static string MenuFetchData {
            get {
                return ResourceManager.GetString("MenuFetchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Home.
        /// </summary>
        internal static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desculpe, não há nada neste endereço..
        /// </summary>
        internal static string RouterNotFound {
            get {
                return ResourceManager.GetString("RouterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione sua localidade.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Responda à nossa {0}breve pesquisa{1} e diga-nos o que pensa..
        /// </summary>
        internal static string SurveyPromptText {
            get {
                return ResourceManager.GetString("SurveyPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Como o Blazor está funcionando para você?.
        /// </summary>
        internal static string SurveyPromptTitle {
            get {
                return ResourceManager.GetString("SurveyPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sobre.
        /// </summary>
        internal static string TopMenuAbout {
            get {
                return ResourceManager.GetString("TopMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data.
        /// </summary>
        internal static string WeatherPageBrowserHeaderDate {
            get {
                return ResourceManager.GetString("WeatherPageBrowserHeaderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resumo.
        /// </summary>
        internal static string WeatherPageBrowserHeaderSummary {
            get {
                return ResourceManager.GetString("WeatherPageBrowserHeaderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Temperatura (C).
        /// </summary>
        internal static string WeatherPageBrowserHeaderTempC {
            get {
                return ResourceManager.GetString("WeatherPageBrowserHeaderTempC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Temperatura (F).
        /// </summary>
        internal static string WeatherPageBrowserHeaderTempF {
            get {
                return ResourceManager.GetString("WeatherPageBrowserHeaderTempF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este componente demonstra a obtenção de dados do servidor..
        /// </summary>
        internal static string WeatherPageDescription {
            get {
                return ResourceManager.GetString("WeatherPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Previsão do tempo.
        /// </summary>
        internal static string WeatherPageTitlle {
            get {
                return ResourceManager.GetString("WeatherPageTitlle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bem-vindo ao seu novo aplicativo..
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
