//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationImoveis.Localization;
/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resource_es {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resource_es() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication.Localization.Resource_es", typeof(Resource_es).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Haz click en mi.
    /// </summary>
    internal static string CounterPageLabelButtonClick {
        get {
            return ResourceManager.GetString("CounterPageLabelButtonClick", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Recuento actual.
    /// </summary>
    internal static string CounterPageLabelCurrrentCount {
        get {
            return ResourceManager.GetString("CounterPageLabelCurrrentCount", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Encimera.
    /// </summary>
    internal static string CounterPageTitle {
        get {
            return ResourceManager.GetString("CounterPageTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to ¡Hola, Mundo!.
    /// </summary>
    internal static string Greeting {
        get {
            return ResourceManager.GetString("Greeting", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to ¿Cómo funciona Blazor para ti? Responda nuestra breve encuesta y díganos lo que piensa..
    /// </summary>
    internal static string HomeText {
        get {
            return ResourceManager.GetString("HomeText", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Perfil evaluado.
    /// </summary>
    internal static string IndexAssessedProfile {
        get {
            return ResourceManager.GetString("IndexAssessedProfile", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cargando....
    /// </summary>
    internal static string Loading {
        get {
            return ResourceManager.GetString("Loading", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Encimera.
    /// </summary>
    internal static string MenuCounter {
        get {
            return ResourceManager.GetString("MenuCounter", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Obtener datos.
    /// </summary>
    internal static string MenuFetchData {
        get {
            return ResourceManager.GetString("MenuFetchData", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Hogar.
    /// </summary>
    internal static string MenuHome {
        get {
            return ResourceManager.GetString("MenuHome", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Lo siento, no hay nada en esta dirección..
    /// </summary>
    internal static string RouterNotFound {
        get {
            return ResourceManager.GetString("RouterNotFound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Seleccione su localidad.
    /// </summary>
    internal static string SelectLanguage {
        get {
            return ResourceManager.GetString("SelectLanguage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Realice nuestra {0}breve encuesta{1} y díganos lo que piensa..
    /// </summary>
    internal static string SurveyPromptText {
        get {
            return ResourceManager.GetString("SurveyPromptText", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to ¿Cómo funciona Blazor para ti?.
    /// </summary>
    internal static string SurveyPromptTitle {
        get {
            return ResourceManager.GetString("SurveyPromptTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Acerca de.
    /// </summary>
    internal static string TopMenuAbout {
        get {
            return ResourceManager.GetString("TopMenuAbout", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Fecha.
    /// </summary>
    internal static string WeatherPageBrowserHeaderDate {
        get {
            return ResourceManager.GetString("WeatherPageBrowserHeaderDate", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Resumen.
    /// </summary>
    internal static string WeatherPageBrowserHeaderSummary {
        get {
            return ResourceManager.GetString("WeatherPageBrowserHeaderSummary", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Temperatura (C).
    /// </summary>
    internal static string WeatherPageBrowserHeaderTempC {
        get {
            return ResourceManager.GetString("WeatherPageBrowserHeaderTempC", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Temperatura (F).
    /// </summary>
    internal static string WeatherPageBrowserHeaderTempF {
        get {
            return ResourceManager.GetString("WeatherPageBrowserHeaderTempF", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Este componente demuestra cómo obtener datos del servidor..
    /// </summary>
    internal static string WeatherPageDescription {
        get {
            return ResourceManager.GetString("WeatherPageDescription", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Pronóstico del tiempo.
    /// </summary>
    internal static string WeatherPageTitlle {
        get {
            return ResourceManager.GetString("WeatherPageTitlle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Bienvenido a tu nueva aplicación..
    /// </summary>
    internal static string Wellcome {
        get {
            return ResourceManager.GetString("Wellcome", resourceCulture);
        }
    }
}
